//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feroza.MultiParts.Infrastructure.Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MultiPartesContext : DbContext
    {
        public MultiPartesContext()
            : base("name=MultiPartesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicaciones> Aplicaciones { get; set; }
        public virtual DbSet<CatalogoDetalles> CatalogoDetalles { get; set; }
        public virtual DbSet<Catalogos> Catalogos { get; set; }
        public virtual DbSet<EstadoMaestras> EstadoMaestras { get; set; }
        public virtual DbSet<Fabricantes> Fabricantes { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Referencias> Referencias { get; set; }
        public virtual DbSet<Sistemas> Sistemas { get; set; }
        public virtual DbSet<SubSistemas> SubSistemas { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
        public virtual DbSet<VehiculoSistemas> VehiculoSistemas { get; set; }
        public virtual DbSet<VehiculoSubSistemas> VehiculoSubSistemas { get; set; }
    }
}
